# Generated by Django 5.0.1 on 2024-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
    ]
