# Generated by Django 5.0.1 on 2024-01-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(db_column='id_componente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('sestado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioProducto',
            fields=[
                ('id_horarioproducto', models.AutoField(db_column='id_horarioproducto', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horarioproducto',
                'managed': False,
            },
        ),
    ]
