# Generated by Django 5.0.1 on 2024-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_detalleensamblecomponente_detalleensambleproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsambleUnidadMedida',
            fields=[
                ('ideum', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadconversion', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'ensambleunidadmedida',
                'managed': False,
            },
        ),
    ]
