# Generated by Django 5.0.1 on 2024-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('estado', models.CharField(choices=[('E', 'E'), ('D', 'D'), ('F', 'F')], max_length=1)),
            ],
            options={
                'db_table': 'reservaciones',
                'managed': False,
            },
        ),
    ]
