# Generated by Django 5.0.2 on 2024-02-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesero', '0002_detallefactura_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id_notacredito', models.AutoField(primary_key=True, serialize=False)),
                ('id_factura', models.IntegerField()),
                ('fechaemision', models.DateTimeField()),
                ('motivo', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('A', 'A'), ('C', 'C')], max_length=1)),
            ],
            options={
                'db_table': 'notacredito',
                'managed': False,
            },
        ),
    ]
