# Generated by Django 5.0.1 on 2024-01-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoSector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleGeosector',
            fields=[
                ('id_detallegeosector', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_geosector',
                'managed': False,
            },
        ),
    ]
