# Generated by Django 5.0 on 2025-02-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motorizado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_motorizado', models.ForeignKey(db_column='id_motorizado', on_delete=django.db.models.deletion.CASCADE, to='Motorizado.motorizados')),
            ],
            options={
                'db_table': 'caja_diaria',
                'managed': True,
                'unique_together': {('id_motorizado', 'fecha')},
            },
        ),
    ]
