# Generated by Django 5.0 on 2025-02-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motorizado', '0002_cajadiaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajadiaria',
            options={'managed': False},
        ),
    ]
